#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ping -c 5 "$1"

# This script checks whether a host is reachable on the network by sending 5 ping requests to the provided IP address.
