#!/usr/bin/env bash

sudo cp /etc/hosts /etc/hosts.bak

sudo sed -i '/localhost/d' /etc/hosts
sudo sed -i '/facebook\.com/d' /etc/hosts

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
