#!/usr/bin/env bash
# Configures /etc/hosts so localhost and facebook.com resolve to custom IPs

sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
sudo sed -i '/facebook\.com/d' /etc/hosts

echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
